### ISSUE TITLE
many "failed to reconcile resource"

### ISSUE THREAD

**Issue by prune998** [banzaicloud/kafka-operator#104]
**Describe the bug**
When creating a cluster (deploying the CR), I get many errors like : 
```
"error":"failed to reconcile resource: updating cr with rack awareness info failed: fetching Node rack awareness labels failed: Node \"\" not found"
```
and
```
"error":"failed to reconcile resource: updating resource failed: Service \"kf-kafka2-112\" is invalid: [metadata.ownerReferences.apiVersion: Invalid value: \"\": version must not be empty, metadata.ownerReferences.kind: Invalid value: \"\": kind must not be empty]"
```

**Steps to reproduce the issue:**
upload a CR like : 

```
apiVersion: banzaicloud.banzaicloud.io/v1alpha1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kf-kafka2
spec:
  headlessServiceEnabled: false
  zkAddresses:
    - "test-zookeeper-client.alerting:2181"
  rackAwareness:
    labels:
      - "failure-domain.beta.kubernetes.io/region"
      - "failure-domain.beta.kubernetes.io/zone"
  oneBrokerPerNode: false
  brokerConfigs:
    - image: "wurstmeister/kafka:2.12-2.1.0"
      id: 111
      resourceReqs:
        limits:
          memory: "2Gi"
        requests:
          memory: "2Gi"
          cpu: "1"
      config: |
        auto.create.topics.enable=false
        delete.topic.enable=true
        num.partitions=32
        default.replication.factor=2
        offsets.topic.replication.factor=2
        transaction.state.log.replication.factor=2
        transaction.state.log.min.isr=1
        ProducerConfig.RETRIES_CONFIG=10
        ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG=1000
        session.timeout.ms=200000
        num.recovery.threads.per.data.dir=8
      storageConfigs:
        - mountPath: "/kafka-logs"
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: ssd
            resources:
              requests:
                storage: 256Gi
...
```

**Expected behavior**
there should not be any error

**Additional context**
K8s cluster on AKS 1.14.5
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
