### ISSUE TITLE
can't set imagePullSecrets in Kafka pods

### ISSUE THREAD

**Issue by prune998** [banzaicloud/kafka-operator#106]
**Is your feature request related to a problem? Please describe.**
Pods support a `imagePullSecrets` option to set the secret(s) to use so it can pull the image from a private registry.
This feature is not provided by the `KafkaCluster` definition.

**Describe the solution you'd like to see**
Add a `imagePullSecrets` field in the `KafkaCluster` CRD which should be an array like : 
```
 imagePullSecrets:
  - name: private-docker-registry-key

```

**Describe alternatives you've considered**
The only other solution is to create a `ServiceAccount` and add the `imagePullSecrets` to it, then use it in the `KafkaCluster`

like : 
```
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app: kafkacluster
    name: kafkacluster
    namespace: kafka
  imagePullSecrets:
  - name: private-docker-registry-key
```
