### ISSUE TITLE
External SSL not working with internal plaintext

### ISSUE THREAD

**Issue by rpahli** [banzaicloud/kafka-operator#164]
**Describe the bug**
I have a cluster with a lisnter config like this:

```
  listenersConfig:
    externalListeners:
      - type: "ssl"
        name: "ssl"
        externalStartingPort: 19090
        containerPort: 9094
    internalListeners:
      - type: "plaintext"
        name: "plaintext"
        containerPort: 29092
        usedForInnerBrokerCommunication: true
    sslSecrets:
      tlsSecretName: "test-kafka-operator"
      jksPasswordName: "test-kafka-operator-pass"
      create: true
```
When the controller starts to create the cluster it will only create one broker and the it can't connect to this broker because it trys to connect with the tls cert but the broker starts a plaintext port. 

I added a check to the kafka client creation:

```
if cluster.Spec.ListenersConfig.SSLSecrets != nil && cluster.Spec.ListenersConfig.InternalListeners[0].Type != "plaintext" {
```

Would it be ok to change the code for ssl check?
