### ISSUE TITLE
new storageclass missing parameter

### ISSUE THREAD

**Issue by todd-dsm** [banzaicloud/kafka-operator#175]
in the readme.md, under the **Installation** section:
_We recommend to use a custom StorageClass..._

`metadata:` is missing. Please update:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:                                               # add this line
  name: exampleStorageclass
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
