### ISSUE TITLE
Broker pod disappeared after node reboot

### ISSUE THREAD

**Issue by YanzheL** [banzaicloud/kafka-operator#237]
**Describe the bug**

For a healthy `KafkaCluster`, if I reboot one of broker nodes, the broker pod of that node disappeared. It seems that the pod is deleted permanently and this situation will not recover.
However, the PVC of that pod still exists.
No new broker pod will be created, so I'm going to lose a broker once I reboot the node.
This is a really serious problem.

**Steps to reproduce the issue:**

1. Create a `KafkaCluster` resource with at lease 3 brokers and no `externalListeners`

2. After the cluster is properly setup, reboot one of the broker nodes, the pod will be recreated after that node is running. Everything is good so far.

3. Add `externalListeners` to the resource definition and re-apply it.

    ```yaml
    externalListeners:
      - type: "ssl"
        name: "external"
        externalStartingPort: 19090
        containerPort: 29092
    sslSecrets:
      tlsSecretName: "kafka-operator"
      jksPasswordName: "helloword!"
      create: true
    ```

4. We will see a `envoy-loadbalancer` service is in pending state because it's waiting for external ip assignment.

    So I modified the `envoy-loadbalancer` service manually, and add `externalIPs` field value to it.

    ```yaml
    kind: Service
    apiVersion: v1
    ...
    spec:
      ...
      externalIPs:
        - 10.245.144.201        # This is a routable IP from our subnet. Actually, this is a virtual IP. But I think it's irrelevant. In this case, we just regard it as a properly configured external IP.
      ...
    ```

    Now, the LB service status is Ok. I can access the service via `10.245.144.201`.

5. Now, the weird thing happens. If I delete one of broker pods or reboot the broker node, that pod will never recreate. No new broker pod, either.

**Expected behavior**

The (new) broker pod will be automatically recreated after node reboot or pod deletion.

**Additional context**

Kubernetes Version: 1.16.3
kafka-operator version: 0.8.1

BTW, how can I see the debug log of kafka-operator? The console output of kafka-operator pod is just two lines of INFO logs.
