### ISSUE TITLE
I am not able to run Zookeeper as adviced in the documentation

### ISSUE THREAD

**Issue by smiklosovic** [banzaicloud/kafka-operator#244]
Hi,

the docs say that one has to install Zookeeper first. Fair enough.

I was trying to do it with helm 3 approach but all the time I am not able to provision that because I can not claim any volume to that.

I was doing:

```
kubectl create --namespace zookeeper -f - <<EOF
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper-cluster
  namespace: zookeeper
spec:
  replicas: 1
EOF
```

This results in:

```
[smiklosovic@E091-FED k8s]$ kubectl -n zookeeper describe persistentvolumeclaims 
Name:          data-zookeeper-cluster-0
Namespace:     zookeeper
StorageClass:  
Status:        Pending
Volume:        
Labels:        app=zookeeper-cluster
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    zookeeper-cluster-0
Events:
  Type    Reason         Age                   From                         Message
  ----    ------         ----                  ----                         -------
  Normal  FailedBinding  105s (x223 over 56m)  persistentvolume-controller 
 no persistent volumes available for this claim and no storage class is set
```
That is strange! So I dig deeper and I look into `master` branch of that repository where I see https://github.com/pravega/zookeeper-operator/blob/master/pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go#L70

Hrm, so what about specify just that persistence somehow, e.g. like this and we should be good right ..

```
kubectl create --namespace zookeeper -f - <<EOF
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper-cluster
  namespace: zookeeper
spec:
  replicas: 1
  persistence:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
EOF
```
So I look into helm charts what version I am actually installing and it is 0.2.0 when there is already 0.2.4 and they changed `persistence` to `spec` in 0.2.1 (you can find it yourself, a commit about pv deletion policy)

https://github.com/banzaicloud/banzai-charts/blob/master/zookeeper-operator/values.yaml#L9

More to it, I am not completely sure this makes sense but after looking into its crd, it seems like it is very obsolete, isnt it?

I tried to `operator-sdk generate openapi` but it failed as I guess my version of operator sdk is incompatible with the code which is in zookeeper-operator repository.

How do you actually run this? It seems to me that zookeeper as of now is "uninstallable"

I created ticket there too https://github.com/pravega/zookeeper-operator/issues/114

**Comment by smiklosovic** [comment]
https://github.com/pravega/zookeeper-operator/issues/114

**Comment by stoader** [comment]
This doesn't seem to be an issue related to Zookeeper but rather your Kubernetes cluster not being able to provision PVs.

1. What Kubernetes distribution are you using?
1. What is your Kubernetes version?
1. Are you on a multi-availability zone setup?
1. Do you have a `(default)` storage class defined in your cluster? `kubectl get sc`

**Comment by smiklosovic** [comment]
@stoader 

what I did is that I used their zookeeper-operator and I overrode image.tag to latest and then I applied this and it seems to work. I am not completely sure what additional value banzai's zookeeper-operator Helm chart brings to the table as I do not think, as of now, it would work for me as there is not that `persistence` field in spec, is it ...

```
kubectl create --namespace default -f - <<EOF
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper-cluster
  namespace: default
spec:
  replicas: 1
  persistence:
    reclaimPolicy: Delete
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
EOF
```

**Comment by stoader** [comment]
We developed the helm chart for zookeeper-operator as the time we developer kafka-operator there was no official helm chart for zookeeper-operator.


The error message above `
`` Type    Reason         Age                   From                         Message
  ----    ------         ----                  ----                         -------
  Normal  FailedBinding  105s (x223 over 56m)  persistentvolume-controller 
 no persistent volumes available for this claim and no storage class is set``` clearly indicates that a storage class is missing (see `no storage class is set`) that's why Kubernetes can't honour the  PVC request.

You either create a `default` storage class within your Kubernetes cluster (this is why I asked to check if you have a default storage class in your cluster) or if you have a different storage class (other than default) already set up in your cluster than pass it to 

```
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper-cluster
  namespace: zookeeper
spec:
  replicas: 1
  persistence:
    storageClassName: <my-custom-storage-class>
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
```

Our kafka-operator doesn't require to deploy zookeeper with out Helm chart. You can deploy Zookeeper using the official Helm chart. You just need to specify in the `KafkaCluster` the address where Zookeeper is reachable.
