### ISSUE TITLE
Assign permissions to KafkaUser based on topicName regex match

### ISSUE THREAD

**Issue by YanzheL** [banzaicloud/kafka-operator#269]
**Is your feature request related to a problem? Please describe.**

Currently, the `topicGrants` for a `KafkaUser` need to assigned to each `topicName` explicitly. There is no method to assign a permission to a range of topics base on `topicName` regex match. This problem brings much inconvenience for user management. 

**Describe the solution you'd like to see**

For example, I want to create a KafkaUser `test` that has write permission to all topics whose name has a `test` prefix.

```yaml
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaUser
metadata:
  name: test
spec:
  clusterRef:
    name: kafka
  secretName: test
  topicGrants:
    - topicName: test.*
      accessType: write
```

So I don't need to change the configuration of the `KafkaUser` when I add a new topic with `test` prefix. Permissions will be automatically granted to the user.

**Describe alternatives you've considered**

Simple wildcard match is also welcome if regex match is not possible.

**Additional context**
