### ISSUE TITLE
Adjusting storage request in KafkaCluster BrokerConfig does not update PVC

### ISSUE THREAD

**Issue by SapientGuardian** [banzaicloud/kafka-operator#346]
**Describe the bug**
Adjusting the storage request in the brokerConfigGroups default storageConfigs does not update PVCs that have already been created

**Steps to reproduce the issue:**
Create a KafkaCluster with something like this:
```
apiVersion: kafka.banzaicloud.io/v1beta1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kafka
spec:
...
  brokerConfigGroups:
    default:
...
      storageConfigs:
        - mountPath: "/kafka-logs"          
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: 'gp2wfc'
...
```

After the cluster has been created, and everything is stable, update the configuration to increase the storage request, e.g.  
```
apiVersion: kafka.banzaicloud.io/v1beta1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: kafka
spec:
...
  brokerConfigGroups:
    default:
...
      storageConfigs:
        - mountPath: "/kafka-logs"          
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 40Gi
            storageClassName: 'gp2wfc'
...
```

**Expected behavior**
I expected the PVCs which got created along with the cluster to update their capacity (which can be done online as of Kubernetes 1.15 https://kubernetes.io/docs/concepts/storage/persistent-volumes/#resizing-a-volume-containing-a-file-system). Instead, the cluster seemed to do a rolling restart, but the PVCs did not change their capacity.

**Additional context**
Manually resizing the PVCs worked just fine, so it's an easy enough workaround.
