### ISSUE TITLE
CruiseControl deployment/pod should be restarted when cruiseControlConfig.config field is updated in KafkaCluster CR

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/kafka-operator#371]
**Description**

Cruise-Control pod part of a Deployment is correctly restarted when `cruiseControlConfig.capacityConfig` field in KafkaCluster is updated.
However this is not happening when `cruiseControlConfig.config` field is updated.

**Describe the solution you'd like to see**
Similar to
```yaml
  template:
    metadata:
      annotations:
        cruiseControlCapacity.json: <sha>
```
the operator should add add `cruiseControlConfig` annotation to the CruiseControl `Deployment` so whenever the CC properties are updated the Deployment should trigger a restart of the CC `Pod`

**Alternatives**
Cumbersome, mess with the Deployment itself but this is not ideal
