### ISSUE TITLE
Gitops tools keep reporting CRDs as out-of-sync due to status field

### ISSUE THREAD

**Issue by abyth** [banzaicloud/kafka-operator#389]
**Describe the bug**
CRDs contain status information that are subject to change once they are applied to a cluster. Gitops tools like argo-cd detect those changes and mark the entries as out-of-sync

**Steps to reproduce the issue:**
* Install argo-cd e.g. as described here https://argoproj.github.io/argo-cd/getting_started/
* Deploy the banzaicloud kafka-operator using helm:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/kafka-operator
    repoURL: https://github.com/banzaicloud/kafka-operator.git
    targetRevision: v0.12.0
  syncPolicy:
    automated: {}
```
* Check the argo-cd web-ui and check the kafka-operator application
<img width="1916" alt="Screenshot 2020-06-05 at 17 54 23" src="https://user-images.githubusercontent.com/6534038/83897255-a590a400-a755-11ea-9163-e36acc1028ca.png">
<img width="1489" alt="Screenshot 2020-06-05 at 17 47 42" src="https://user-images.githubusercontent.com/6534038/83896881-1d120380-a755-11ea-9f61-7be20a3dec70.png">

**Expected behavior**
CRDs do not contain information that are subject to change, allowing gitops tools like argo-cd to successfully manage them and keep them in-sync

**Additional context**
argo-cd: v1.5.2
kafka-operator: v0.12.0
