### ISSUE TITLE
Configurable prometheus operator annotations

### ISSUE THREAD

**Issue by azun** [banzaicloud/kafka-operator#398]
**Is your feature request related to a problem? Please describe.**
Currently Kafka brokers and CruiseControl are monitored using prometheus annotations (`prometheus.io/scrape=true`). These annotations are hardcoded in the operator and offer limited options for configuration (lack of scrape interval/timeout configs, relabelling, isolation etc).

**Describe the solution you'd like to see**
Ideally the annotations should be configurable by the user as an opt-in or opt-out

```
# opt-in
spec:
  brokerConfigGroups:
    default:
      brokerAnnotations:
        prometheus.io/port: 9020
        prometheus.io/scrape: true
  cruiseControlConfig:
    annotations:
      prometheus.io/port: 9020
      prometheus.io/scrape: true

# opt-out
spec:
  brokerConfigGroups:
    default:
      externalMonitoring: true
  cruiseControlConfig:
    externalMonitoring: true
```

ServiceMonitors would then be created separately 

**Describe alternatives you've considered**
N/A

**Additional context**
The documentation actually instructs to create [ServiceMonitors](https://github.com/banzaicloud/kafka-operator/blob/master/config/samples/kafkacluster-prometheus.yaml) but doing so would duplicate the metrics in prometheus. Disabling annotation scraping would fix this but it's not desirable.
