### ISSUE TITLE
KafkaCluster upscale cannot be cancelled or updated

### ISSUE THREAD

**Issue by amuraru** [banzaicloud/kafka-operator#400]
**Is your feature request related to a problem? Please describe.**
KafkaCluster upscale cannot be cancelled or updated.

**Describe the solution you'd like to see**
There are cases where a cluster upscale (adding more brokers) needs to be cancelled or updated.

Here is an contrived example just to make the testing easier (other legitimate similar use-cases exists):
1. Start with a healthy `KafkaCluster` with say 3 broker groups, 1 broker in each broker group:
 - broker-group1: b101
 - broker-group2: b201
 - broker-group3: b301
 
2. Initiate an upscale by creating a new broker-group4 and add 1 broker to it.
To simulate this behaviour I created the `broker-group4` using a nodeSelector for an invalid availability zone
```yaml
azInvalid:
     ...
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: us-east-1-invalid 
```

3. At this stage the KafkaCluster has the following config:
```yaml
  brokers:
    - brokerConfigGroup: az1
      id: 101
      readOnlyConfig: |
        broker.rack=us-east-1a
    - brokerConfigGroup: az2
      id: 201
      readOnlyConfig: |
        broker.rack=us-east-1b
    - brokerConfigGroup: az3
      id: 301
      readOnlyConfig: |
        broker.rack=us-east-1c
    - brokerConfigGroup: azInvalid
      id: 401
```
The operator is:
- creating the new broker Pod but this stays in `Pending` as the nodeSelector cannot be fullfiled by k8s scheduler (this can happen in reality due to lack of resources in cluster, etc)
- creating a new entry in CR `status.brokersState`:
```yaml
"401":
      configurationState: ConfigInSync
      gracefulActionState:
        cruiseControlState: GracefulUpscaleRequired
        errorMessage: ""
      rackAwarenessState: ""
```
- trying to add the broker in CruiseControl

```text
2020-06-24T16:13:39.970Z	DEBUG	controller.CruiseControlTask	Reconciling	{"clusterName": "pipeline-kafka", "clusterNamespace": "ns-team-aep-pipeline-kafka-1-dev"}
2020-06-24T16:13:39.974Z	INFO	controller.CruiseControlTask	cruise control communication error during upscaling broker(s)	{"clusterName": "pipeline-kafka", "clusterNamespace": "ns-team-aep-pipeline-kafka-1-dev", "brokerId(s)": ["401"]}
```
The behaviour is expected, the broker pod is not yet started, it didn't join kafka cluster so it's not visible by CC either.

4. *At this stage* I want to *cancel* the up-scale and revert to previous state where only 3 brokers are in cluster.
I remov broker `401` from KafkaCluster CR 
```yaml
    - brokerConfigGroup: azInvalid
      id: 401
```
And nothing happens. The operator keeps trying to add broker 401 to CC which of course is not possible because broker has not yet joined cluster/cc.
Tried even to delete externally the Pending pod broker-401. Once deleted, it's not being recreated by the operator(good!)
but its entry in  CR `status.brokersState`  (`cruiseControlState: GracefulUpscaleRequired`) remains so the operator keeps trying to add it to CC.

Even worse - At this point any new upscale/downscale operation cannot be performed until that rogue broker is sorted out.
The only workaround is to create that exact broker id in a different broker group so the operator gets out of this deadlock.

Studying this behaviour it seems to be in this situation the `status.brokersState` got out of sync from the `spec` and there should be a way to re-sync it. IIUC the source of truth remains the `spec.brokers` so the state should be reconciled from it.
