### ISSUE TITLE
cannot change healthCheckNodePort on loadBalancer service with externalTraffic=Local during update

### ISSUE THREAD

**Issue by Deepak1100** [banzaicloud/kafka-operator#546]
**Describe the bug**
I am seeing below error in operator logs 
```
 {"level":"error","ts":"2021-02-01T08:37:19.296Z","logger":"controller","msg":"Reconciler error","reconcilerGroup":"kafka.banzaicloud.io","reconcilerKind":"KafkaCluster","controller":"KafkaCluster","name":"kafka","namespace":"kafka","error":"updating resource failed: Service \"envoy-loadbalancer-external-1-kafka\" is invalid: spec.healthCheckNodePort: Invalid value: 0: cannot change healthCheckNodePort on loadBalancer service with externalTraffic=Local during update","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:246\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:90"}
```

config
```
      - type: "ssl"
        name: "external-1"
        containerPort: 9092
        accessMethod: LoadBalancer 
        externalStartingPort: 32000
        externalTrafficPolicy: "Local" # either Local or Cluster. If omitted defaults to Cluster.
        hostnameOverride: "kafka.my.domain"
    sslSecrets:
      # tlsSecretName should contain all ssl certs required by kafka including: caCert, caKey, clientCert, clientKey
      # serverCert, serverKey, peerCert, peerKey
      tlsSecretName: "kafka-tls"
      # jksPasswordName should contain a password field which contains the jks password
      jksPasswordName: "kafka-jks"
      # create tells the installed cert manager to create the required certs keys
      create: true
  envoyConfig:
   replicas: 1
   resourceRequirements:
     limits:
       memory: "300Mi"
       cpu: "200m"
     requests:
       memory: "300Mi"
       cpu: "200m"
   annotations:
     external-dns.alpha.kubernetes.io/hostname: kafka.my.domain
     external-dns.alpha.kubernetes.io/ttl: "60"
     service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
     service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "120"
     service.beta.kubernetes.io/aws-load-balancer-internal: "true"
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: mycert
     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: http
```
**Screenshots**

Operator version
```
kafka-operator:v0.14.0
```
k8s Version
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:52:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
we have setup k8s on AWS using kops.
